services:
  mongo:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: password 
      MONGO_INITDB_DATABASE: leaderboardDB
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - spring-boot-network
  
  spring-boot-app:
    container_name: codehack
    image: codehack
    ports:
      - "8080:8080"
    networks:
      - spring-boot-network
    depends_on:
      - mongo 

volumes:
  mongo_data:


networks:
  spring-boot-network:
    driver: bridge